/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AtmBank;

/**
 *
 * @author ASUS
 */
public class Tranfer2 extends javax.swing.JFrame {

    /**
     * Creates new form Tranfer2
     */
    public Tranfer2() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jumtransfer = new javax.swing.JTextField();
        Benar = new javax.swing.JButton();
        salah = new javax.swing.JButton();
        sisa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(573, 403));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Masukkan Jumlah Transfer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 90, 220, 22);

        jumtransfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jumtransfer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jumtransferInputMethodTextChanged(evt);
            }
        });
        jumtransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumtransferActionPerformed(evt);
            }
        });
        jPanel1.add(jumtransfer);
        jumtransfer.setBounds(190, 130, 170, 40);

        Benar.setText("Transfer");
        Benar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenarActionPerformed(evt);
            }
        });
        jPanel1.add(Benar);
        Benar.setBounds(220, 190, 110, 23);

        salah.setText("Kembali");
        salah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salahActionPerformed(evt);
            }
        });
        jPanel1.add(salah);
        salah.setBounds(430, 310, 90, 23);

        sisa.setText("Sisa Saldo Anda");
        jPanel1.add(sisa);
        sisa.setBounds(140, 230, 260, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenarActionPerformed
        // TODO add your handling code here:
        TransferModel tf = new TransferModel();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        String jmlh = jumtransfer.getText();
        double jmlh2 = Double.parseDouble(jmlh);
        tf.transfer = jmlh2;
        double s = Double.parseDouble(saldo.getSaldo());
        double hasil = s- tf.transfer;
        if(tf != null){
            sisa.setVisible(true);
            sisa.setText("SISA SALDO ANDA : Rp "+hasil);
        }else{
            sisa.setVisible(false);}
    }//GEN-LAST:event_BenarActionPerformed

    private void jumtransferInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jumtransferInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumtransferInputMethodTextChanged

    private void salahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salahActionPerformed
        // TODO add your handling code here:
        new Pinn().setVisible(true);
    }//GEN-LAST:event_salahActionPerformed

    private void jumtransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumtransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumtransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tranfer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tranfer2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Benar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumtransfer;
    private javax.swing.JButton salah;
    private javax.swing.JLabel sisa;
    // End of variables declaration//GEN-END:variables
}
